
ccflags-$(CONFIG_ARCH_MULTIPLATFORM) := -I$(srctree)/$(src)/include

obj-$(CONFIG_ARCH_CTR) += main_ctr.o
obj-$(CONFIG_ARCH_CTR) += bottom_lcd.o
obj-$(CONFIG_ARCH_CTR) += early_console.o
obj-$(CONFIG_SMP) += platsmp.o
obj-$(CONFIG_SMP) += headsmp.o
